const meal = {
  idMeal: '52987',
  strMeal: 'Lasagna Sandwiches',
  strDrinkAlternate: null,
  strCategory: 'Pasta',
  strArea: 'American',
  strInstructions:
    '1. In a small bowl, combine the first four ingredients; spread on four slices of bread. Layer with bacon, tomato and cheese; top with remaining bread.\r\n\r\n2. In a large skillet or griddle, melt 2 tablespoons butter. Toast sandwiches until lightly browned on both sides and cheese is melted, adding butter if necessary.\r\n\r\nNutrition Facts\r\n1 sandwich: 445 calories, 24g fat (12g saturated fat), 66mg cholesterol, 1094mg sodium, 35g carbohydrate (3g sugars, 2g fiber), 21g protein.',
  strMealThumb:
    'https://www.themealdb.com/images/media/meals/xr0n4r1576788363.jpg',
  strTags: 'Sandwich',
  strYoutube: '',
  strIngredient1: 'Sour Cream',
  strIngredient2: 'Chopped Onion',
  strIngredient3: 'Dried Oregano',
  strIngredient4: 'Salt',
  strIngredient5: 'Bread',
  strIngredient6: 'Bacon',
  strIngredient7: 'Tomato',
  strIngredient8: 'Mozzarella',
  strIngredient9: 'Butter',
  strIngredient10: '',
  strIngredient11: '',
  strIngredient12: '',
  strIngredient13: '',
  strIngredient14: '',
  strIngredient15: '',
  strIngredient16: '',
  strIngredient17: '',
  strIngredient18: '',
  strIngredient19: '',
  strIngredient20: '',
  strMeasure1: '1/4 cup',
  strMeasure2: '2 tbs',
  strMeasure3: '1/2 tbs',
  strMeasure4: '1/4 tsp',
  strMeasure5: '8 slices',
  strMeasure6: '8 slices',
  strMeasure7: '8 slices',
  strMeasure8: '4 slices',
  strMeasure9: '2 1/2 Tbs',
  strMeasure10: ' ',
  strMeasure11: ' ',
  strMeasure12: ' ',
  strMeasure13: ' ',
  strMeasure14: ' ',
  strMeasure15: ' ',
  strMeasure16: ' ',
  strMeasure17: ' ',
  strMeasure18: ' ',
  strMeasure19: ' ',
  strMeasure20: ' ',
  strSource: '',
  strImageSource: null,
  strCreativeCommonsConfirmed: null,
  dateModified: null,
}
